# Generated by Django 5.1.2 on 2024-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='datetime',
            new_name='commenttimestamp',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='datetime',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image/'),
        ),
    ]
