# Generated by Django 5.1.2 on 2024-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentdislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentlike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postdislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postlike',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
