# Generated by Django 5.1.2 on 2024-11-20 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comments_commentdislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked',
            field=models.ManyToManyField(related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
