# Generated by Django 5.1.2 on 2024-11-25 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_posts_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentdislike',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='postdislike',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(related_name='profile_posts', to='network.posts')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
