# Generated by Django 5.1.2 on 2024-11-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_comments_commentdislike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='avt',
            field=models.ImageField(default='defaultavt.jpg', upload_to='profile_avt'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
