# Generated by Django 5.1.2 on 2024-11-30 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_username_profile_user_profile_avt_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='postlike',
            new_name='no_of_like',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='liked',
        ),
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(default=None, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
